### ISSUE TITLE
setup failed

### ISSUE THREAD

**Issue by derricktsmith** [rwieruch/gatsby-mdx-blog-starter-project#3]
Trying an initial setup. After `yarn && yarn develop` I got this on `localhost:8000`

![](https://sh-drop.s3.us-east-1.amazonaws.com/ds/non-keep/Screen%20Shot%202019-04-19%20at%204.10.11%20PM.png)

What gives? 😄

**Comment by rwieruch** [comment]
Hm, not sure what happened here. Some time ago that I used this project. Did you start to debug it?

**Comment by rwieruch** [comment]
I tried it and it worked for me. Anyway, I updated all libraries to their recent version. Maybe you want to give it another try.
