### ISSUE TITLE
Is gatsby-transformer-remark necessary?

### ISSUE THREAD

**Issue by kuworking** [rwieruch/gatsby-mdx-blog-starter-project#4]
I can't find where is `gatsby-transformer-remark` used here, even though it is in `package.json`

Is it unnecessary when using `gatsby-mdx`?

(perhaps related, https://github.com/gatsbyjs/gatsby/issues/12656)

**Comment by rwieruch** [comment]
Did you try removing it? :)

**Comment by kuworking** [comment]
Never, I wouldn't dare :)
