### ISSUE TITLE
Set failed 3 times

### ISSUE THREAD

**Issue by zzrez** [rwieruch/gatsby-mdx-blog-starter-project#6]
I used both **git clone** and **gatsby new** to create locally. Each time the home page loaded badly as seen in image. I also cloned another Gatsby MDX starter without any problem whatsoever. I suggest this starter be well tested, and perhaps hosting on netlify so people can see what it does before cloning.

![bad-site](https://user-images.githubusercontent.com/11816764/67254227-3457e700-f439-11e9-8013-1c394269c43d.PNG)

**Comment by rwieruch** [comment]
It comes with all the features, but it's not styled.
